[workspace]
members = [
    "kernel",
    "kernel/lib",
    "shared",
    "apps/shared_lib",
    "apps/rpn",
    "apps/large",
    "apps/winhello",
    "apps/stars",
    "apps/lines",
    "apps/eye"
]
