[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
# https://os.phil-opp.com/minimal-rust-kernel/#set-a-default-target
target = "target.json"
