name: Push Check

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none

    - name: setup
      run: |
        git submodule update --init --recursive
        ./kernel/usb/setup.sh
        sudo apt-get install nasm

    - name: fmt
      run: cargo fmt -- --check

    - name: run tests
      run: cargo test --target x86_64-unknown-linux-gnu -Z build-std --verbose
      working-directory: ./kernel/lib/
