[package]
name = "rpn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
apps = { path = "../../apps", version = "0.1.0" }